# Built with Jekyll 3.2.0

# Setup
title:               Bayes4ie
tagline:             'A gentle(ish) introduction to the use of Bayesian analysis for impact evaluations'
description:         'Site based on the Ed theme.'
url:                 'https://dougj892.github.io/bayes4ie2/'
baseurl:             ''

# About/contact
author:
  name:              Doug Johnson
  url:               https://twitter.com/dougj8921
  email:             dougj892@gmail.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  syntax_highlighter: rouge

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


